apiVersion: v1
kind: Service
metadata:
  name: {{ include "chat-app-chart.fullname" . }}-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "chat-app-chart.name" . }}-frontend