apiVersion: v2
name: chat-app
description: A Helm chart for deploying a realtime chat application
version: 0.1.0  # Increment with each release
appVersion: "1.0"  # Version of your application
dependencies:
  - name: redis
    version: "17.0.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled  # Optional Redis for realtime features