apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
      
      annotations:
        kubectl.kubernetes.io/restartedAt: "{{ now | date '2006-01-02T15:04:05Z07:00' }}"
    spec:
      containers:
      - name: backend
        image: chat-app-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 4000
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: MONGODB_URI
          value: "mongodb://root:chatdb123@mongodb:27017/chatdb?authSource=admin"
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 10