apiVersion: v1
kind: Service
metadata:
  name: {{ include "chat-app-chart.fullname" . }}-mongodb
spec:
  type: {{ .Values.mongodb.service.type }}
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.service.targetPort }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "chat-app-chart.name" . }}-mongodb